[package]
name = "rust-mean"
version = "0.1.0"
authors = ["boa <rubberboa01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-mean"
path = "main.rs"
